# This is a basic workflow to reward your developers with cryptocurrency using Perk.Exchange

name: Perk.Exchange

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  rewards:
    runs-on: ubuntu-latest
    steps:
      # Rewards the initiating user with cryptocurrency       
      - uses: perkexchange/github-action@v0.7-alpha
        name: Perk.Exchange Reward
        with:
            apiToken: ${{ secrets.PERKEXCHANGE_APITOKEN }}
            campaignReference: ${{ secrets.PERKEXCHANGE_CAMPAIGNREFERENCE }}
            userId: ${{ github.event.sender.id }}
            platform: github
            amount: 3
            server: https://9c7d-99-251-23-45.ngrok.io
